"$schema" = "node_modules/wrangler/config-schema.json"
name = "advanced-payment-dashboard"
# main = "dist/server/server.js"
main = "@tanstack/react-start/server-entry"

compatibility_date = "2025-09-02"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "dist/client"

[observability]
enabled = true

# [[kv_namespaces]]
# binding = "CACHE"
# id = "<Your KV ID>"

[vars]
BACKEND_API = "https://hlx9bszx46.execute-api.ap-northeast-1.amazonaws.com/"
COGNITO_USER_POOL_ID = "ap-northeast-1_xxxxxxxxx"
COGNITO_CLIENT_ID = "xxxxxxxxxxxxxxxxxxxxxxxxxx"