"$schema" = "node_modules/wrangler/config-schema.json"
name = "advanced-payment-dashboard"
main = ".output/server/index.mjs"
compatibility_date = "2025-07-30"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".output/public"

[observability]
enabled = true

# [[kv_namespaces]]
# binding = "CACHE"
# id = "<Your KV ID>"

[vars]
BACKEND_API = "https://hlx9bszx46.execute-api.ap-northeast-1.amazonaws.com/"